# Which agentic-lib workflow schedule should be used?
schedule: schedule-2
sourcesLimit: 128
documentsLimit: 8
featuresWipLimit: 2
featureDevelopmentIssuesWipLimit: 6
maintenanceIssuesWipLimit: 2
attemptsPerBranch: 2
attemptsPerIssue: 2
writeableFilepaths:
  docs:         "README.md"
  features:     "features/"
  library:      "library/"
  src:          "src/lib/main.js"
  tests:        "tests/unit/main.test.js"
  dependencies: "package.json"
  readme:       "README.md"
  sources:      "SOURCES.md"
