# Which agentic-lib workflow schedule should be used?
schedule: schedule-4
featuresWipLimit: 2
featureDevelopmentIssuesWipLimit: 6
maintenanceIssuesWipLimit: 2
attemptsPerBranch: 2
attemptsPerIssue: 2
