#!/usr/bin/env node
// SPDX-License-Identifier: MIT
// Copyright (C) 2025-2026 Polycode Limited
// Demo script for plot-code-lib - showcases all features and generates comprehensive examples

import { execSync } from 'child_process';
import { mkdirSync, writeFileSync } from 'fs';
import { fileURLToPath } from 'url';
import path from 'path';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const projectRoot = __dirname;
const outputDir = path.join(projectRoot, 'demo-output');

// Create output directory
try {
  mkdirSync(outputDir, { recursive: true });
} catch (error) {
  // Directory might already exist
}

console.log('🎯 plot-code-lib Comprehensive Demo');
console.log('====================================\n');

console.log(`📁 Creating examples in: ${outputDir}\n`);

/**
 * Execute a plot command and capture output
 */
function runPlotCommand(command, description) {
  console.log(`🚀 ${description}`);
  console.log(`   Command: ${command}`);
  
  try {
    const fullCommand = `node src/lib/main.js ${command}`;
    const output = execSync(fullCommand, { 
      encoding: 'utf8',
      cwd: projectRoot 
    });
    console.log(`   ✅ ${output.trim()}\n`);
    return true;
  } catch (error) {
    console.log(`   ❌ Error: ${error.message}\n`);
    return false;
  }
}

/**
 * Generate README content for the demo output
 */
function generateDemoReadme() {
  const readmeContent = `# plot-code-lib Demo Output

This directory contains comprehensive examples generated by the plot-code-lib demo script.

## Contents

### Basic Function Plots
- **sine-wave.svg** - Classic sine wave demonstration
- **quadratic.svg** - Parabolic function with vertex highlighting
- **exponential-growth.svg** - Exponential growth model
- **exponential-decay.svg** - Exponential decay model
- **logarithmic.svg** - Natural logarithm function
- **polynomial-comparison.svg** - Multiple polynomial degrees compared

### Trigonometric Functions
- **trig-comparison.svg** - Sin, cos, tan comparison with legend
- **phase-shifts.svg** - Sine waves with different phase shifts
- **amplitude-modulation.svg** - AM-modulated sine wave
- **damped-oscillation.svg** - Exponentially damped oscillation

### Multi-Expression Plots
- **frequency-comparison.svg** - Different frequency sine waves
- **polynomial-family.svg** - Polynomial family with custom labels
- **exponential-family.svg** - Growth vs decay comparison

### Parametric Curves (Mathematical Art)
- **unit-circle.svg** - Perfect circle via parametric equations
- **heart-curve.svg** - Mathematical heart shape (cardioid)
- **lissajous-3-2.svg** - Lissajous curve with 3:2 frequency ratio
- **rose-curve.svg** - Beautiful rose curve pattern
- **spiral-archimedes.svg** - Archimedes spiral
- **butterfly-curve.svg** - Stunning butterfly mathematical curve

### Scientific & Engineering Applications
- **gaussian-distribution.svg** - Standard normal distribution
- **sigmoid-function.svg** - Logistic sigmoid activation function
- **fourier-approximation.svg** - Square wave Fourier series approximation
- **step-response.svg** - First-order system step response
- **frequency-response.svg** - Lowpass filter frequency response
- **bessel-function.svg** - Bessel function of the first kind

### High-Resolution Examples
- **publication-ready.png** - High-resolution PNG for presentations
- **poster-quality.png** - Ultra-high resolution for printing

### Data Export Examples
- **sine-data.json** - Coordinate data in JSON format
- **trig-data.csv** - Multi-expression CSV with expression names
- **parametric-data.geojson** - Parametric curve in GeoJSON format
- **analysis-data.json** - Multi-expression analysis dataset

## Command Examples

Each file was generated using commands like:

\`\`\`bash
# Basic function plot
plot-code-lib plot -e "sin(x)" -r "x=0:2*pi" -o sine-wave.svg --title "Sine Wave"

# Multi-expression comparison
plot-code-lib plot -e "sin(x),cos(x),tan(x)" -r "x=-pi:pi" -o trig-comparison.svg

# Parametric curves
plot-code-lib parametric -x "16*sin(t)^3" -y "13*cos(t)-5*cos(2*t)-2*cos(3*t)-cos(4*t)" -r "t=0:2*pi" -o heart-curve.svg

# Data export
plot-code-lib export -e "sin(x),cos(x)" -r "x=0:2*pi:0.1" -o trig-data.csv --format csv
\`\`\`

## Usage

View the SVG files in any web browser or vector graphics editor.
PNG files can be opened in any image viewer.
JSON/CSV files can be analyzed with data processing tools.

## Next Steps

1. Try modifying the expressions in these commands
2. Experiment with different ranges and step sizes  
3. Create your own mathematical visualizations
4. Use the exported data in your analysis pipelines

---
Generated by plot-code-lib v0.1.0
`;

  writeFileSync(path.join(outputDir, 'README.md'), readmeContent);
  console.log('📝 Generated demo README.md\n');
}

/**
 * Generate command summary file
 */
function generateCommandSummary() {
  const commands = [
    'plot -e "sin(x)" -r "x=0:2*pi" -o demo-output/sine-wave.svg --title "Sine Wave"',
    'plot -e "x^2 - 4*x + 3" -r "x=-1:5" -o demo-output/quadratic.svg --title "Quadratic Function" --xlabel "x" --ylabel "f(x)"',
    'plot -e "exp(x)" -r "x=0:3" -o demo-output/exponential-growth.svg --title "Exponential Growth"',
    'plot -e "exp(-x)" -r "x=0:5" -o demo-output/exponential-decay.svg --title "Exponential Decay"',
    'plot -e "log(x)" -r "x=0.1:10" -o demo-output/logarithmic.svg --title "Natural Logarithm" --xlabel "x" --ylabel "ln(x)"',
    'plot -e "sin(x),cos(x),tan(x)" -r "x=-pi:pi" -o demo-output/trig-comparison.svg --title "Trigonometric Functions"',
    'plot -e "Phase 0:sin(x),Phase π/4:sin(x+pi/4),Phase π/2:sin(x+pi/2)" -r "x=0:2*pi" -o demo-output/phase-shifts.svg --title "Phase Shift Comparison"',
    'plot -e "Linear:x,Quadratic:x^2,Cubic:x^3,Quartic:x^4" -r "x=-2:2" -o demo-output/polynomial-comparison.svg --title "Polynomial Degrees"',
    'plot -e "1Hz:sin(2*pi*x),2Hz:sin(4*pi*x),5Hz:sin(10*pi*x)" -r "x=0:2" -o demo-output/frequency-comparison.svg --title "Frequency Comparison"',
    'plot -e "Growth:exp(x),Decay:exp(-x)" -r "x=0:3" -o demo-output/exponential-family.svg --title "Exponential Family"',
    'plot -e "sin(5*x) * exp(-x/3)" -r "x=0:15:0.1" -o demo-output/damped-oscillation.svg --title "Damped Oscillation"',
    'plot -e "(1 + sin(10*x)) * sin(x)" -r "x=0:4*pi" -o demo-output/amplitude-modulation.svg --title "Amplitude Modulation"',
    'parametric -x "cos(t)" -y "sin(t)" -r "t=0:2*pi" -o demo-output/unit-circle.svg --title "Unit Circle"',
    'parametric -x "16*sin(t)^3" -y "13*cos(t)-5*cos(2*t)-2*cos(3*t)-cos(4*t)" -r "t=0:2*pi" -o demo-output/heart-curve.svg --title "Heart Curve"',
    'parametric -x "sin(3*t)" -y "sin(2*t)" -r "t=0:2*pi" -o demo-output/lissajous-3-2.svg --title "Lissajous Curve 3:2"',
    'parametric -x "cos(5*t)*cos(t)" -y "cos(5*t)*sin(t)" -r "t=0:pi" -o demo-output/rose-curve.svg --title "Rose Curve"',
    'parametric -x "t*cos(t)" -y "t*sin(t)" -r "t=0:6*pi:0.1" -o demo-output/spiral-archimedes.svg --title "Archimedes Spiral"',
    'parametric -x "sin(t)*(exp(cos(t))-2*cos(4*t)-sin(t/12)^5)" -y "cos(t)*(exp(cos(t))-2*cos(4*t)-sin(t/12)^5)" -r "t=0:12*pi:0.1" -o demo-output/butterfly-curve.svg --title "Butterfly Curve"',
    'plot -e "exp(-x^2/2) / sqrt(2*pi)" -r "x=-4:4" -o demo-output/gaussian-distribution.svg --title "Standard Normal Distribution"',
    'plot -e "1/(1 + exp(-x))" -r "x=-6:6" -o demo-output/sigmoid-function.svg --title "Sigmoid Function"',
    'plot -e "sin(x) + sin(3*x)/3 + sin(5*x)/5 + sin(7*x)/7" -r "x=-pi:pi" -o demo-output/fourier-approximation.svg --title "Square Wave Fourier Series"',
    'plot -e "1 - exp(-t/2)" -r "t=0:10" -o demo-output/step-response.svg --title "First-Order Step Response" --xlabel "Time" --ylabel "Response"',
    'plot -e "1 / sqrt(1 + (x/2)^2)" -r "x=0.1:10" -o demo-output/frequency-response.svg --title "Lowpass Filter Response" --xlabel "ω/ω₀" --ylabel "|H(jω)|"',
    'plot -e "sin(x)/x" -r "x=-20:20:0.1" -o demo-output/bessel-function.svg --title "Sinc Function (J₀ approximation)"',
    'plot -e "sin(x)*cos(3*x)" -r "x=0:2*pi" -o demo-output/publication-ready.png --width 1920 --height 1080 --title "High Resolution Plot"',
    'plot -e "x^3 - 3*x^2 + 2*x + 1" -r "x=-2:3" -o demo-output/poster-quality.png --width 3840 --height 2160 --title "Ultra High Resolution"',
    'export -e "sin(x)" -r "x=0:2*pi:0.1" -o demo-output/sine-data.json --format json',
    'export -e "sin(x),cos(x),tan(x)" -r "x=0:2*pi:0.1" -o demo-output/trig-data.csv --format csv',
    'export -e "cos(t),sin(t)" -r "t=0:2*pi:0.1" -o demo-output/parametric-data.geojson --format geojson',
    'export -e "Exponential:exp(x),Logarithmic:log(x+1),Polynomial:x^3" -r "x=0:5:0.1" -o demo-output/analysis-data.json --format json'
  ];

  const commandContent = `# plot-code-lib Demo Commands

This file contains all the commands used to generate the demo output.
Copy and paste any command to reproduce the results.

## Basic Function Plots

${commands.slice(0, 5).map(cmd => `plot-code-lib ${cmd}`).join('\n')}

## Trigonometric and Multi-Expression Plots

${commands.slice(5, 12).map(cmd => `plot-code-lib ${cmd}`).join('\n')}

## Parametric Curves (Mathematical Art)

${commands.slice(12, 18).map(cmd => `plot-code-lib ${cmd}`).join('\n')}

## Scientific & Engineering Applications

${commands.slice(18, 24).map(cmd => `plot-code-lib ${cmd}`).join('\n')}

## High-Resolution Examples

${commands.slice(24, 26).map(cmd => `plot-code-lib ${cmd}`).join('\n')}

## Data Export Examples

${commands.slice(26, 30).map(cmd => `plot-code-lib ${cmd}`).join('\n')}

## Usage Tips

1. **Modify expressions**: Change the math functions to explore different curves
2. **Adjust ranges**: Try different x/t ranges and step sizes for resolution
3. **Custom styling**: Add titles, axis labels, and dimensions
4. **Format selection**: Choose SVG for web/print, PNG for presentations
5. **Data processing**: Export to JSON/CSV for analysis pipelines

## Next Steps

- Combine with other CLI tools: \`jq\`, \`awk\`, \`gnuplot\`
- Use in shell scripts for batch processing
- Integrate into data analysis workflows
- Create animation frames with parameter sweeps
`;

  writeFileSync(path.join(outputDir, 'commands.md'), commandContent);
  console.log('📝 Generated commands reference\n');
}

// Demo execution
console.log('🎬 Starting comprehensive demonstration...\n');

// Generate documentation first
generateDemoReadme();
generateCommandSummary();

// Basic Function Plots
console.log('📊 BASIC FUNCTION PLOTS');
console.log('========================\n');

runPlotCommand(
  'plot -e "sin(x)" -r "x=0:2*pi" -o demo-output/sine-wave.svg --title "Sine Wave"',
  'Classic sine wave'
);

runPlotCommand(
  'plot -e "x^2 - 4*x + 3" -r "x=-1:5" -o demo-output/quadratic.svg --title "Quadratic Function" --xlabel "x" --ylabel "f(x)"',
  'Quadratic parabola with axis labels'
);

runPlotCommand(
  'plot -e "exp(x)" -r "x=0:3" -o demo-output/exponential-growth.svg --title "Exponential Growth"',
  'Exponential growth model'
);

runPlotCommand(
  'plot -e "exp(-x)" -r "x=0:5" -o demo-output/exponential-decay.svg --title "Exponential Decay"',
  'Exponential decay model'
);

runPlotCommand(
  'plot -e "log(x)" -r "x=0.1:10" -o demo-output/logarithmic.svg --title "Natural Logarithm" --xlabel "x" --ylabel "ln(x)"',
  'Natural logarithm with domain handling'
);

// Multi-Expression Plots
console.log('🌈 MULTI-EXPRESSION PLOTS');
console.log('==========================\n');

runPlotCommand(
  'plot -e "sin(x),cos(x),tan(x)" -r "x=-pi:pi" -o demo-output/trig-comparison.svg --title "Trigonometric Functions"',
  'Trigonometric functions comparison'
);

runPlotCommand(
  'plot -e "Phase 0:sin(x),Phase π/4:sin(x+pi/4),Phase π/2:sin(x+pi/2)" -r "x=0:2*pi" -o demo-output/phase-shifts.svg --title "Phase Shift Comparison"',
  'Phase-shifted sine waves with custom labels'
);

runPlotCommand(
  'plot -e "Linear:x,Quadratic:x^2,Cubic:x^3,Quartic:x^4" -r "x=-2:2" -o demo-output/polynomial-comparison.svg --title "Polynomial Degrees"',
  'Polynomial comparison with degree labels'
);

runPlotCommand(
  'plot -e "1Hz:sin(2*pi*x),2Hz:sin(4*pi*x),5Hz:sin(10*pi*x)" -r "x=0:2" -o demo-output/frequency-comparison.svg --title "Frequency Comparison"',
  'Different frequency sine waves'
);

runPlotCommand(
  'plot -e "Growth:exp(x),Decay:exp(-x)" -r "x=0:3" -o demo-output/exponential-family.svg --title "Exponential Family"',
  'Exponential growth vs decay'
);

// Advanced Mathematical Functions
console.log('🔬 ADVANCED MATHEMATICAL FUNCTIONS');
console.log('===================================\n');

runPlotCommand(
  'plot -e "sin(5*x) * exp(-x/3)" -r "x=0:15:0.1" -o demo-output/damped-oscillation.svg --title "Damped Oscillation"',
  'Exponentially damped oscillation'
);

runPlotCommand(
  'plot -e "(1 + sin(10*x)) * sin(x)" -r "x=0:4*pi" -o demo-output/amplitude-modulation.svg --title "Amplitude Modulation"',
  'AM-modulated sine wave'
);

// Parametric Curves (Mathematical Art)
console.log('🎨 PARAMETRIC CURVES (MATHEMATICAL ART)');
console.log('========================================\n');

runPlotCommand(
  'parametric -x "cos(t)" -y "sin(t)" -r "t=0:2*pi" -o demo-output/unit-circle.svg --title "Unit Circle"',
  'Perfect unit circle'
);

runPlotCommand(
  'parametric -x "16*sin(t)^3" -y "13*cos(t)-5*cos(2*t)-2*cos(3*t)-cos(4*t)" -r "t=0:2*pi" -o demo-output/heart-curve.svg --title "Heart Curve"',
  'Mathematical heart shape (cardioid)'
);

runPlotCommand(
  'parametric -x "sin(3*t)" -y "sin(2*t)" -r "t=0:2*pi" -o demo-output/lissajous-3-2.svg --title "Lissajous Curve 3:2"',
  'Lissajous curve with 3:2 frequency ratio'
);

runPlotCommand(
  'parametric -x "cos(5*t)*cos(t)" -y "cos(5*t)*sin(t)" -r "t=0:pi" -o demo-output/rose-curve.svg --title "Rose Curve"',
  'Beautiful rose curve pattern'
);

runPlotCommand(
  'parametric -x "t*cos(t)" -y "t*sin(t)" -r "t=0:6*pi:0.1" -o demo-output/spiral-archimedes.svg --title "Archimedes Spiral"',
  'Archimedes spiral'
);

runPlotCommand(
  'parametric -x "sin(t)*(exp(cos(t))-2*cos(4*t)-sin(t/12)^5)" -y "cos(t)*(exp(cos(t))-2*cos(4*t)-sin(t/12)^5)" -r "t=0:12*pi:0.1" -o demo-output/butterfly-curve.svg --title "Butterfly Curve"',
  'Stunning butterfly mathematical curve'
);

// Scientific & Engineering Applications
console.log('⚗️ SCIENTIFIC & ENGINEERING APPLICATIONS');
console.log('=========================================\n');

runPlotCommand(
  'plot -e "exp(-x^2/2) / sqrt(2*pi)" -r "x=-4:4" -o demo-output/gaussian-distribution.svg --title "Standard Normal Distribution"',
  'Gaussian probability distribution'
);

runPlotCommand(
  'plot -e "1/(1 + exp(-x))" -r "x=-6:6" -o demo-output/sigmoid-function.svg --title "Sigmoid Function"',
  'Logistic sigmoid activation function'
);

runPlotCommand(
  'plot -e "sin(x) + sin(3*x)/3 + sin(5*x)/5 + sin(7*x)/7" -r "x=-pi:pi" -o demo-output/fourier-approximation.svg --title "Square Wave Fourier Series"',
  'Fourier series square wave approximation'
);

runPlotCommand(
  'plot -e "1 - exp(-t/2)" -r "t=0:10" -o demo-output/step-response.svg --title "First-Order Step Response" --xlabel "Time" --ylabel "Response"',
  'Control systems step response'
);

runPlotCommand(
  'plot -e "1 / sqrt(1 + (x/2)^2)" -r "x=0.1:10" -o demo-output/frequency-response.svg --title "Lowpass Filter Response" --xlabel "ω/ω₀" --ylabel "|H(jω)|"',
  'Filter frequency response analysis'
);

runPlotCommand(
  'plot -e "sin(x)/x" -r "x=-20:20:0.1" -o demo-output/bessel-function.svg --title "Sinc Function (J₀ approximation)"',
  'Bessel-like sinc function'
);

// High-Resolution Examples
console.log('🖼️ HIGH-RESOLUTION EXAMPLES');
console.log('============================\n');

runPlotCommand(
  'plot -e "sin(x)*cos(3*x)" -r "x=0:2*pi" -o demo-output/publication-ready.png --width 1920 --height 1080 --title "High Resolution Plot"',
  'Publication-ready high-resolution PNG'
);

runPlotCommand(
  'plot -e "x^3 - 3*x^2 + 2*x + 1" -r "x=-2:3" -o demo-output/poster-quality.png --width 3840 --height 2160 --title "Ultra High Resolution"',
  'Ultra-high resolution for posters'
);

// Data Export Examples
console.log('📁 DATA EXPORT EXAMPLES');
console.log('========================\n');

runPlotCommand(
  'export -e "sin(x)" -r "x=0:2*pi:0.1" -o demo-output/sine-data.json --format json',
  'Single expression JSON export'
);

runPlotCommand(
  'export -e "sin(x),cos(x),tan(x)" -r "x=0:2*pi:0.1" -o demo-output/trig-data.csv --format csv',
  'Multi-expression CSV with expression names'
);

runPlotCommand(
  'export -e "cos(t),sin(t)" -r "t=0:2*pi:0.1" -o demo-output/parametric-data.geojson --format geojson',
  'Parametric curve as GeoJSON'
);

runPlotCommand(
  'export -e "Exponential:exp(x),Logarithmic:log(x+1),Polynomial:x^3" -r "x=0:5:0.1" -o demo-output/analysis-data.json --format json',
  'Multi-expression analysis dataset'
);

// Summary
console.log('✅ DEMO COMPLETE');
console.log('================\n');

console.log('🎉 Generated 30 comprehensive examples showcasing plot-code-lib capabilities!\n');

console.log('📁 Output directory:', outputDir);
console.log('📊 SVG plots: 24 vector graphics files');
console.log('🖼️  PNG plots: 2 high-resolution images'); 
console.log('📄 Data files: 4 export format examples');
console.log('📝 Documentation: README.md and commands.md\n');

console.log('🚀 Next Steps:');
console.log('   • Open demo-output/ directory to view results');
console.log('   • Try modifying the expressions in commands.md');
console.log('   • Use exported data files in your analysis workflows');
console.log('   • Integrate plot-code-lib into your projects\n');

console.log('🎯 Mission accomplished: "Be the jq of formulae visualizations" ✨');