# Which agentic-lib workflow schedule should be used?
schedule: schedule-3

# Mapping for from symbolic keys to filepaths for access by agentic-lib workflows with limits and access permissions
paths:
  # Filepaths for elaborator workflows
  missionFilepath:
    path: MISSION.md
  librarySourcesFilepath:
    path: SOURCES.md
    limit: 32
    permissions:
      - write
  libraryDocumentsPath:
    path: library/
    limit: 8
    permissions:
      - write
  featuresPath:
    path: features/
    limit: 2
    permissions:
      - write

  # Filepaths for engineer workflows
  contributingFilepath:
    path: CONTRIBUTING.md
  allTestsPaths:
    paths:
      - tests/unit/
  targetTestsPath:
    path: tests/unit/
    permissions:
      - write
  allSourcePaths:
    paths:
      - src/lib/
  targetSourcePath:
    path: src/lib/
    permissions:
      - write
  dependenciesFilepath:
    path: package.json
  documentationPath:
    path: docs/
    permissions:
      - write

  # Filepaths for maintainer workflows
  formattingFilepath:
    path: .prettierrc
  lintingFilepath:
    path: eslint.config.js
  readmeFilepath:
    path: README.md

# Execution commands
buildScript: "npm run build"
testScript: "npm test"
mainScript: "npm run start"

# How many issues should be open to be picked up?
featureDevelopmentIssuesWipLimit: 4
maintenanceIssuesWipLimit: 2

# How many attempts should be made to work on an issue?
attemptsPerBranch: 2
attemptsPerIssue: 2

# Web publishing
docRoot: public
