# Which agentic-lib workflow schedule should be used?
schedule: schedule-3

# Mapping for from symbolic keys to filepaths for access by agentic-lib workflows with limits and access permissions
paths:
  # Filepaths for elaborator workflows
  missionFilepath:
    path: MISSION.md
  librarySourcesFilepath:
    path: LIBRARY_SOURCES.md
    limit: 16
    permissions:
      - write
  libraryDocumentsPath:
    path: LIBRARY_DOCUMENT.md
    limit: 1
    permissions:
      - write
  featuresPath:
    path: PLOT_GENERATION.md
    limit: 1
    permissions:
      - write

  # Filepaths for engineer workflows
  contributingFilepath:
    path: CONTRIBUTING.md
  allTestsPaths:
    paths:
      - tests/unit/main.test.js
      - tests/unit/plot-generation.test.js
  targetTestsPath:
    path: tests/unit/plot-generation.test.js
    permissions:
      - write
  allSourcePaths:
    paths:
      - src/lib/
  targetSourcePath:
    path: src/lib/main.js
    permissions:
      - write
  dependenciesFilepath:
    path: package.json
    permissions:
      - write
  documentationPath:
    path: USAGE.md
    permissions:
      - write

  # Filepaths for maintainer workflows
  formattingFilepath:
    path: .prettierrc
  lintingFilepath:
    path: eslint.config.js
  readmeFilepath:
    path: README.md
    permissions:
      - write

# Execution commands
buildScript: "npm run build"
testScript: "npm test"
mainScript: "npm run start"

# How many issues should be open to be picked up?
featureDevelopmentIssuesWipLimit: 4
maintenanceIssuesWipLimit: 2

# How many attempts should be made to work on an issue?
attemptsPerBranch: 2
attemptsPerIssue: 2

# Web publishing
docRoot: public
