# Which agentic-lib workflow schedule should be used?
schedule: schedule-3

# Mapping for from symbolic keys to filepaths for access by agentic-lib workflows with limits and access permissions
paths:
  # Filepaths for elaborator workflows
  missionFilepath:
    path: 'MISSION.md'
  librarySourcesFilepath:
    path: 'SOURCES.md'
    permissions: [ 'write' ]
    limit: 16
  libraryDocumentsPath:
    path: 'library/'
    permissions: [ 'write' ]
    limit: 1
  featuresPath:
    path: 'features/'
    permissions: [ 'write' ]
    limit: 2

  # Filepaths for engineer workflows
  contributingFilepath:
    path: 'CONTRIBUTING.md'
  targetTestsPath:
    path: 'tests/unit/plot-generation.test.js'
    permissions: [ 'write' ]
  otherTestsPaths:
    paths: [ 'tests/unit/main.test.js' ]
  targetSourcePath:
    path: 'src/lib/main.js'
    permissions: [ 'write' ]
  otherSourcePaths:
    paths: [ 'src/lib/' ]
  dependenciesFilepath:
    path: 'package.json'
    permissions: [ 'write' ]
  documentationPath:
    path: 'USAGE.md'
    permissions: [ 'write' ]

  # Filepaths for maintainer workflows
  formattingFilepath:
    path: '.prettierrc'
  lintingFilepath:
    path: 'eslint.config.js'
  readmeFilepath:
    path: 'README.md'
    permissions: [ 'write' ]

# Execution commands
buildScript: "npm run build"
testScript: "npm test"
mainScript: "npm run start"

# How many issues should be open to be picked up?
featureDevelopmentIssuesWipLimit: 4
maintenanceIssuesWipLimit: 2

# How many attempts should be made to work on an issue?
attemptsPerBranch: 2
attemptsPerIssue: 2

# Web publishing
docRoot: 'public'

# Repository seeding
seeding:
  repositoryReseed: 'true'
  missionFilepath: 'seeds/zero-MISSION.md'
  sourcePath: 'seeds/zero-main.js'
  testsPath: 'seeds/zero-tests.js'
  dependenciesFilepath: 'seeds/zero-package.json'
  readmeFilepath: 'seeds/zero-README.md'

discussionBot:
  seedDiscussionFilepath: 'SEED_DISCUSSION.md'
